version: "3.2"

services:
  phabdev-db:
    build:
      context: .
      dockerfile: mariadb.Dockerfile
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=phabricator_secret
    networks:
      - phabnet
    volumes:
      - db-data:/var/lib/mysql

  phabdev-www:
    build: .
    restart: "no"
    networks:
      - phabnet
    volumes:
      - ./phabricator:$INSTALLDIR/phabricator/
      - ./arcanist:$INSTALLDIR/arcanist/
      - filestore:/opt/filestore/
      - repos:/opt/repos/
    ports:
      - "${PORT}:80"
    environment:
      - INSTALLDIR=${INSTALLDIR}/phabricator
      - HOST=${HOST}
      - PORT=${PORT}

networks:
  phabnet:

volumes:
  db-data:
    name: "phabdev-db"
    external: false
    driver: local

  filestore:
    name: "phabdev-filestore"
    external: false
    driver: local

  repos:
    name: "phabdev-repos"
    external: false
    driver: local
